### ISSUE TITLE
Alfa and Balandro support

### ISSUE THREAD

**Issue by ponchofcult** [mrgsi/tmdbh.players#1]
Hello there! I just wanted to comment that as much as possible I hope you could add support for plugin.video.alfa and plugin.video.balandro they are very good addons and I would like to add them as an option, thanks and regards!

**Comment by mrgsi** [comment]
I would if I could. I can make new players for add-ons made from common templates like an exodus type or a fen fork, but I am lost when it comes to unique add-ons like those. I'm not an actual coder unfortunately,
