### ISSUE TITLE
Update for Gaia Player

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [mrgsi/tmdbh.players#10]
Hi @mrgsi 
This is an update for Gaia player **taking directly from Gaia addon**.

> {
	"name": "[COLOR FFA0C12C]Gaia[/COLOR]",
	"plugin": "plugin.video.gaia",
	"priority": 200,
	"is_resolvable": "false",
	"play_movie": "plugin://plugin.video.gaia/?action=scrape&media=movie&imdb={imdb}&tmdb={tmdb}&tvdb={tvdb}&trakt={trakt}&title={title_url}&year={year}&premiered={premiered}&gaia=True",
	"play_episode": "plugin://plugin.video.gaia/?action=scrape&media=show&imdb={imdb}&tmdb={tmdb}&tvdb={tvdb}&trakt={trakt}&title={title_url}&year={showyear}&premiered={premiered}&season={season}&episode={episode}&tvshowtitle={showname_url}&gaia=True",
	"search_movie": "plugin://plugin.video.gaia/?action=search&media=movie&query={clearname_url}&gaia=True",
	"search_episode": "plugin://plugin.video.gaia/?action=search&media=show&query={clearname_url}&gaia=True"
}

I think it will be better if you made two players (one for playing and the other for searching).

Thanks in advance

**Comment by psp2111-ADSLGATE** [comment]
[gaia.json](https://github.com/mrgsi/tmdbh.players/files/13789875/gaia.json)

**Comment by mrgsi** [comment]
I have updated the old gaia player and added a new search player. Thank you, your input is much appreciated.
