### ISSUE TITLE
Player Request - Jacktook Addon

### ISSUE THREAD

**Issue by jollyhiggler** [mrgsi/tmdbh.players#12]
Hello G Man,

I'd be grateful if you could have a look at the feasibility of adding a player file for the [Jacktook](https://github.com/Sam-Max/plugin.video.jacktook) addon.

Many Thanks

**Comment by mrgsi** [comment]
A player has now been added for the Jacktook add-on, thanks to it's developer, Sam-Max. You can download the player from the list, or extract it from the zip file which was also updated.

**Comment by jollyhiggler** [comment]
Many Thanks
