### ISSUE TITLE
Palantir 3 addon

### ISSUE THREAD

**Issue by kikonou** [mrgsi/tmdbh.players#14]
I have tried to make a manual player for palantir 3 addon (https://github.com/palantirsource/palantir) but it only works with movies (direct play and search works). In tvshow it only works searching by series (not by chapters).

**Comment by mrgsi** [comment]
Sorry, I don't know how that add-on works. You'd need something like:
"play_episode": "plugin://plugin.video.palantir/?mode=playback.media&media_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}". 
Depending on how the add-on was coded of course. Some devs have had to insert code into their add-on to make it compatible with TMDBH. You may have to ask the developer for help.
