### ISSUE TITLE
Eclipse Cinemas 2.0

### ISSUE THREAD

**Issue by TheGridRepo** [mrgsi/tmdbh.players#2]
Not sure if i'm doing this right would it be possiable to add my player to the list.  ( direct.eclipsecinemas_2.0.json )

{
    "name" : "TheGrid: Eclipse Cinemas 2.0",
    "plugin" : "plugin.video.eclipsecinemas_2.0",
    "priority" : 500,
    "play_movie" : "plugin://plugin.video.eclipsecinemas_2.0/?action=play&amp;title={title_+}&amp;year={year}&amp;imdb={imdb}&amp;meta=%7B%22rating%22%3A+%22%22%2C+%22code%22%3A+%22{imdb}%22%2C+%22tmdb%22%3A+%22{id}%22%2C+%22imdb%22%3A+%22{imdb}%22%2C+%22year%22%3A+%22{year}%22%2C+%22duration%22%3A+%22%22%2C+%22plot%22%3A+%22{plot}%22%2C+%22votes%22%3A+%22%22%2C+%22title%22%3A+%22{title_+}%22%2C+%22fanart%22%3A+%22{fanart}%22%2C+%22tagline%22%3A+%22%22%2C+%22writer%22%3A+%22%22%2C+%22next%22%3A+%22%22%2C+%22poster%22%3A+%22{poster}%22%2C+%22mediatype%22%3A+%22movie%22%2C+%22director%22%3A+%22%22%2C+%22studio%22%3A+%22%22%2C+%22genre%22%3A+%22%22%2C+%22metacache%22%3A+true%2C+%22premiered%22%3A+%22{premiered}%22%2C+%22originaltitle%22%3A+%22{title_+}%22%2C+%22cast%22%3A+%5B%5B%22%22%5D%5D%2C+%22mpaa%22%3A+%22%22%2C+%22trailer%22%3A+%22plugin%3A%2F%2Fplugin.video.chucky%2F%3Faction%3Dtrailer%26name%3D{title_+}%2B%2528{year}%2529%22%7D&amp;t={now}",
    "play_episode" : "plugin://plugin.video.eclipsecinemas_2.0/?action=play&amp;title={title_+}&amp;year={year}&amp;imdb={imdb}&amp;tvdb={id}&amp;season={season}&amp;episode={episode}&amp;tvshowtitle={clearname_+}&amp;premiered={firstaired}&amp;meta=%7B%22rating%22%3A+%22%22%2C+%22code%22%3A+%22{imdb}%22%2C+%22tmdb%22%3A+{tmdb}%2C+%22imdb%22%3A+%22{imdb}%22%2C+%22year%22%3A+%22{year}%22%2C+%22duration%22%3A+%22%22%2C+%22plot%22%3A+%22{plot}%22%2C+%22votes%22%3A+%22%22%2C+%22thumb%22%3A+%22{thumbnail}%22%2C+%22title%22%3A+%22{title_+}%22%2C+%22tvdb%22%3A+%22{id}%22%2C+%22label%22%3A+%22{title_+}%22%2C+%22season%22%3A+%22{season}%22%2C+%22status%22%3A+%22%22%2C+%22poster%22%3A+%22{poster}%22%2C+%22tvshowtitle%22%3A+%22{clearname_+}%22%2C+%22mediatype%22%3A+%22episode%22%2C+%22studio%22%3A+%22%22%2C+%22genre%22%3A+%22%22%2C+%22banner%22%3A+%22{thumbnail}%22%2C+%22episode%22%3A+%22{episode}%22%2C+%22premiered%22%3A+%22{firstaired}%22%2C+%22fanart%22%3A+%22{fanart}%22%2C+%22trailer%22%3A+%22plugin%3A%2F%2Fplugin.video.chucky%2F%3Faction%3Dtrailer%26name%3D{clearname_+}%22%7D&amp;t={now}"
}

**Comment by mrgsi** [comment]
Never heard of that add-on. Is it a python 3 add-on? I'm really only supporting players for Kodi 19 and above.

**Comment by TheGridRepo** [comment]
It's my private addon python 3 running k20.1

Sent from AOL on Android 
 
  On Sun, Jun 25, 2023 at 11:20 a.m., ***@***.***> wrote:   


Never heard of that add-on. Is it a python 3 add-on? I'm really only supporting players for Kodi 19 and above.

**Comment by TheGridRepo** [comment]
is there any way to make a player for my addon... tmdbhelper works fine with other players but when create my own using there examples on others here ,its a not go...

**Comment by mrgsi** [comment]
I don't know much about coding players. I can clone some players, like add-ons that are exodus, venom or shadow forks, but nothing unique. The code you are using for your player is for exodus based add-on so I assume yours is as well? I was able to fix the scrubsv2 player when that broke simply by chopping out all the extra metadata that wasn't needed. If your add-on is a fork of an exodus style add-on then you could try a similar code. 

{
  "name" : "Eclipse Cinemas 2.0", 
  "plugin" : "plugin.video.eclipsecinemas_2.0",
  "priority" : 500,
  "is_resolvable" : "true",  
  "play_movie" : "plugin://plugin.video.eclipsecinemas_2.0/?action=play&title={title_+}&year={year}&imdb={imdb}&t={now}",
  "play_episode" : "plugin://plugin.video.eclipsecinemas_2.0/?action=play&title={title_+}&year={year}&imdb={imdb}&tvdb={id}&season={season}&episode={episode}&tvshowtitle={clearname_+}&premiered={firstaired}&t={now}"
}

**Comment by rahaaatul** [comment]
> I don't know much about coding players

@mrgsi Who should we request to create players for addons then?

Also, can you look into the [Dramacool addon](https://github.com/groggyegg/plugin.video.dramacool), if you can make a player for it or not?

**Comment by mrgsi** [comment]
If I come across an add-on that was created as a fork of another add-on that has a player, then I can create a player for that new add-on. If the add-on is custom built by a python coder, then I can't do it. There are no specific people to ask for players, Usually they are created by users who are also coders that donate them to the public, On rare occasions, the add-on developer will create a player for their add-on. I just messaged the dramacool dev and suggested it.
