### ISSUE TITLE
Emby for Kodi Next Gen and Jellyfin

### ISSUE THREAD

**Issue by rahaaatul** [mrgsi/tmdbh.players#3]
Emby: https://emby.media/community/index.php?/topic/116208-embyforkodi-next-gen-8xx-support/
Jellyfin: https://github.com/jellyfin/jellyfin-kodi

I have a large collection in Emby and a small collection in Jellyfin, but I can't play from either of them with TMDB Helper, which I really enjoy using. Please try to make players for them if you could. It would be beneficial for the users. 

Thank you very much.

**Comment by mrgsi** [comment]
The helper has a jellycon and an embycon player built in if you use those add-ons. Beyond that I have zero understanding how they work or how to custom code a player for jellyfin or emby. https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/nexus/resources/players

**Comment by rahaaatul** [comment]
Hello, @mrgsi ! Thank you for responding!

I discovered on the Emby forum that you don't actually need any player for Emby Next Gen and Jellyfin because the contents are synced into Kodi.

>[**quickmic** : Why bother next gen with playback queries if the content is synced into Kodi. Also, not sure why the TMDB Player is not using/searching Kodi database for playback. If this plugin wants to search/play content, it should use Kodi functions as default and only query other plugins if no content found in Kodi's db.](https://emby.media/community/index.php?/topic/106853-embyforkodi-next-gen-7xx-support/&do=findComment&comment=1197207)

I tried that, however TMDB player keeps building players every time I try to play from any TMDB helper widget. Is there any way I can configure that in the settings to allow Kodi to play directly from its database?

**Comment by mrgsi** [comment]
I have no idea on that. I'd suggest asking on the developer's Github or on one of the Kodi sub reddits r/Addons4Kodi, or r/Kodi_Helpers, or r/kodi

**Comment by rahaaatul** [comment]
Thank you for the help anyway! 🙏
