### ISSUE TITLE
Fen Light

### ISSUE THREAD

**Issue by omaramiromo** [mrgsi/tmdbh.players#6]
Not sure if i can make request, but can i request player for Fen Light?

**Comment by mrgsi** [comment]
Sure, I will take a look at it when I can. Right now I can't get Fen or Fenlight to work at all on my PC so can't test a new player. Odd as all the other add-ons work flawlessly.

**Comment by omaramiromo** [comment]
> Sure, I will take a look at it when I can. Right now I can't get Fen or Fenlight to work at all on my PC so can't test a new player. Odd as all the other add-ons work flawlessly.

Fen working flawlessly for me so far. So i think fenlight would be the same

**Comment by mrgsi** [comment]
Not sure what the conflict was, but switched to another setup on my PC and got Fen Light working. I've added a "Fen Light Select" and a "Fen Light AutoPlay" player to the list and the zip file. Both tested and working on my PC.
