### ISSUE TITLE
Player request

### ISSUE THREAD

**Issue by onlytanmoy** [mrgsi/tmdbh.players#8]
Hi, hope you doing well.
Just wanted to check if I can request for creating a player for one of the addons I am using?

**Comment by mrgsi** [comment]
Depends on the add-on. Let me know what it is and I will look into it.

**Comment by onlytanmoy** [comment]
> Depends on the add-on. Let me know what it is and I will look into it.

thanks for your response :) please find add-on link https://github.com/srbaber/xbmc-easynews

**Comment by mrgsi** [comment]
Sorry, can't do it for that one. There are many other add-ons that use the easynews account which do have players.

**Comment by onlytanmoy** [comment]
> Sorry, can't do it for that one. There are many other add-ons that use the easynews account which do have players.

no worries, thanks for checking for me :)
