### ISSUE TITLE
Context menu "Default Player" error

### ISSUE THREAD

**Issue by rhinhold** [mrgsi/tmdbh.players#9]
I installed Kodi (tried different versions) on a Windows 10 system.
After assigning a default player to a show using the context menu. It indicates successfully added. But when starting the show I get error see log notice. I have tried it with Hulu and Seren players. I also attempted to play directly from within the TMDB app instead of the home screen. Currently I have the same setup on Firestick and Tivo devices and all works fine. So not sure if this may be a Windows issue. Any assistance would be appreciated. I have attached log file.

Thank you,
[kodi.log](https://github.com/mrgsi/tmdbh.players/files/13653848/kodi.log)

**Comment by mrgsi** [comment]
Shouldn't be an issue with Windows 10 as that's what I use to test and build with. The first thing I'd try is to play something in Seren. If that works, but the Seren player in the Helper doesn't than it must be an issue with the Helper or the players. Next, I'd go into the Helper settings. Go into "Expert" and delete all cache. Nothing stands out in your log file so I don't know what it could be. You may need to ask jurialmunkey on his github. He wouldn't support the seren player, but he is the one that provides the Hulu player.

**Comment by rhinhold** [comment]
Thanks for the quick reply!

I can run shows in all the players just fine. It’s just from the context menu. When I right click on a show and choose a default player. That’s when I get the error. I can still use choose player from the context menu and runs fine. Just the set default player.

I’ll hit up the other forums in the morning. And buy you guys a coffee.

Thanks again!

Robert

On Dec 12, 2023, at 8:12 PM, G-Man ***@***.***> wrote:

﻿

Shouldn't be an issue with Windows 10 as that's what I use to test and build with. The first thing I'd try is to play something in Seren. If that works, but the Seren player in the Helper doesn't than it must be an issue with the Helper or the players. Next, I'd go into the Helper settings. Go into "Expert" and delete all cache. Nothing stands out in your log file so I don't know what it could be. You may need to ask jurialmunkey on his github. He wouldn't support the seren player, but he is the one that provides the Hulu player.
